version: '3.8'

services:
  trafico-inteligente:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simulador-trafico
    environment:
      - DISPLAY=host.docker.internal:0
    volumes:
      # CÃ³digo fuente montado como solo lectura
      - ./TraficoInteligente/src:/app/src:ro
    # No usar network_mode: host en Windows
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"

